# Generated by Django 3.1.2 on 2021-03-26 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Имя в Viber')),
                ('date_sub', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата подписки')),
                ('image', models.CharField(blank=True, max_length=450, verbose_name='Аватар')),
                ('region', models.CharField(blank=True, max_length=2, verbose_name='Страна')),
                ('phone', models.CharField(blank=True, max_length=14, verbose_name='Телефон')),
                ('source', models.CharField(blank=True, max_length=128, verbose_name='Источник')),
                ('in_use', models.BooleanField(default=True, verbose_name='Подписан')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
