# Generated by Django 3.1.2 on 2021-05-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managers', models.CharField(choices=[('Dri', 'Водители')], default='Dri', max_length=20, unique=True, verbose_name='Водители')),
                ('inuse', models.ManyToManyField(blank=True, to='customer.Subscriber', verbose_name='Список Водителей Маруси')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
    ]
