# Generated by Django 3.1.2 on 2021-09-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='managers',
            field=models.CharField(choices=[('Driver', 'Водители')], default='Driver', max_length=20, unique=True, verbose_name='Водители'),
        ),
    ]
