# Generated by Django 3.1.2 on 2021-09-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210928_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='managers',
            field=models.CharField(choices=[('Dri', 'Водители')], default='Dri', max_length=20, unique=True, verbose_name='Водители'),
        ),
    ]
