# Generated by Django 3.1.2 on 2021-09-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210928_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='managers',
            field=models.CharField(choices=[('Driver', 'Водители')], default='Driver', max_length=20, unique=True, verbose_name='Водители'),
        ),
    ]
