# Generated by Django 3.1.2 on 2022-04-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210928_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['name'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_driver',
            field=models.BooleanField(default=False, verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='Включен'),
        ),
    ]
