# Generated by Django 3.1.2 on 2023-08-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20220422_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='is_driver',
            field=models.BooleanField(default=True, verbose_name='Водитель'),
        ),
    ]
