# Generated by Django 3.1.2 on 2023-10-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_subscriber_snils'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='SNILS',
        ),
    ]
