# Generated by Django 3.1.2 on 2023-10-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_subscriber_snils'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='SNILS',
            field=models.CharField(blank=True, max_length=14, verbose_name='СНИЛС'),
        ),
    ]
