# Generated by Django 3.1.2 on 2023-12-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_subscriber_snils'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='SNILS',
        ),
    ]
