# Generated by Django 3.1.2 on 2023-12-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_subscriber_snils'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='SNILS',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='СНИЛС'),
        ),
    ]
