# Generated by Django 3.1.2 on 2023-12-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_subscriber_snils'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
