# Generated by Django 3.1.2 on 2023-12-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20231214_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='color_for_snils',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='snils_verified',
            field=models.BooleanField(default=False, verbose_name='СНИЛС проверен'),
        ),
    ]
