# Generated by Django 3.1.2 on 2023-12-19 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_auto_20231220_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='last_modify_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего обновления'),
        ),
    ]
