# Generated by Django 3.1.2 on 2024-01-11 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_subscriber_last_modify_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-snils_verified'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
