# Generated by Django 3.1.2 on 2024-01-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20240112_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
    ]
