# Generated by Django 3.1.2 on 2024-01-29 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_subscriber_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSubscribers',
            fields=[
            ],
            options={
                'verbose_name': 'Заблокированный водитель',
                'verbose_name_plural': 'Заблокированные водители',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customer.subscriber',),
        ),
    ]
