# Generated by Django 3.1.2 on 2021-09-27 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210928_0033'),
        ('botviber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionsForRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(default='', max_length=32, verbose_name='Регион')),
                ('condition', models.CharField(default='', max_length=1024, verbose_name='Условие')),
            ],
            options={
                'verbose_name': 'Условие для региона',
                'verbose_name_plural': 'Условия для регионов',
            },
        ),
        migrations.CreateModel(
            name='LicensingQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(choices=[('Напишите свою фамилию и имя', 'Напишите свою фамилию и имя'), ('Напишите свой номер телефона', 'Напишите свой номер телефона'), ('Напишите гос. номер вашего автомобиля', 'Напишите гос. номер вашего автомобиля'), ('Напишите марку и модель вашего автомобиля', 'Напишите марку и модель вашего автомобиля'), ('Отправьте фото первой развёрнутой страницы паспорта', 'Отправьте фото первой развёрнутой страницы паспорта'), ('Отправьте фото паспорта (прописка)', 'Отправьте фото паспорта (прописка)'), ('Отправьте фото лицевой стороны СТС', 'Отправьте лицевой задней стороны СТС'), ('Отправьте фото задней стороны СТС', 'Отправьте фото задней стороны СТС'), ('Ваша заявка отправлена!', 'Ваша заявка отправлена!')], default='', max_length=100, verbose_name='Вопросы')),
            ],
        ),
        migrations.CreateModel(
            name='LicensingQuestionnaireButtons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buttons', models.ManyToManyField(related_name='licensing_buttons', to='botviber.Button')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.subscriber')),
            ],
            options={
                'verbose_name': 'Кнопки с вопросами',
                'verbose_name_plural': 'Кнопки с вопросами',
            },
        ),
    ]
