# Generated by Django 3.1.2 on 2021-09-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botviber', '0002_conditionsforregions_licensingquestionnairebuttons_licensingquestions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConditionsForRegions',
        ),
        migrations.RemoveField(
            model_name='licensingquestionnairebuttons',
            name='buttons',
        ),
        migrations.RemoveField(
            model_name='licensingquestionnairebuttons',
            name='user',
        ),
        migrations.DeleteModel(
            name='LicensingQuestions',
        ),
        migrations.DeleteModel(
            name='LicensingQuestionnaireButtons',
        ),
    ]
