# Generated by Django 3.1.2 on 2021-11-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210928_2033'),
        ('botviber', '0004_conditionsforregions_licensingquestionnairebuttons_licensingquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaybillQuestionnaireButtons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit', models.BooleanField(default=False)),
                ('buttons', models.ManyToManyField(related_name='waybill_buttons', to='botviber.Button')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.subscriber')),
            ],
            options={
                'verbose_name': 'Кнопка с вопросом для заказа путёвки',
                'verbose_name_plural': 'Кнопки с вопросами для заказа путёвки',
            },
        ),
    ]
