# Generated by Django 3.1.2 on 2021-11-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botviber', '0005_waybillquestionnairebuttons'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaybillQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(choices=[('Напишите вашу фамилию', 'Напишите вашу фамилию'), ('Напишите ваше имя', 'Напишите ваше имя'), ('Напишите ваше отчество', 'Напишите ваше отчество'), ('Серия водительского удостоверения', 'Серия водительского удостоверения'), ('Номер водительского удостоверения', 'Номер водительского удостоверения'), ('Класс ТС (B, C... )', 'Класс ТС (B, C... )'), ('Гос. номер ТС', 'Гос. номер ТС'), ('Марка ТС', 'Марка ТС'), ('Показание одометра', 'Показание одометра'), ('Ваша заявка отправлена!', 'Ваша заявка отправлена!')], default='', max_length=100, verbose_name='Вопросы')),
            ],
        ),
    ]
