# Generated by Django 3.1.2 on 2022-04-22 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20220422_1607'),
        ('botviber', '0007_auto_20211222_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCreateQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(choices=[('Напишите марку автомобиля', 'Напишите марку автомобиля'), ('Напишите модель автомобиля', 'Напишите модель автомобиля'), ('Напишите номер автомобиля', 'Напишите номер автомобиля'), ('Сохранить', 'Сохранить')], default='', max_length=100, verbose_name='Сообщения при нажатии на кнопки меню создания автомобиля')),
            ],
        ),
        migrations.AlterModelOptions(
            name='licensingquestionnairebuttons',
            options={'verbose_name': 'Кнопка формы лицензии', 'verbose_name_plural': 'Кнопки формы лицензии'},
        ),
        migrations.AlterField(
            model_name='licensingquestions',
            name='questions',
            field=models.CharField(choices=[('Напишите своё имя', 'Напишите своё имя'), ('Напишите свою фамилию', 'Напишите свою фамилию'), ('Напишите свой номер телефона', 'Напишите свой номер телефона'), ('Напишите гос. номер вашего автомобиля', 'Напишите гос. номер вашего автомобиля'), ('Напишите марку вашего автомобиля', 'Напишите марку вашего автомобиля'), ('Напишите модель вашего автомобиля', 'Напишите модель вашего автомобиля'), ('Отправьте фото первой развёрнутой страницы паспорта', 'Отправьте фото первой развёрнутой страницы паспорта'), ('Отправьте фото паспорта (прописка)', 'Отправьте фото паспорта (прописка)'), ('Отправьте фото лицевой стороны СТС', 'Отправьте лицевой задней стороны СТС'), ('Отправьте фото задней стороны СТС', 'Отправьте фото задней стороны СТС'), ('Ваша заявка отправлена!', 'Ваша заявка отправлена!')], default='', max_length=100, verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='waybillquestions',
            name='questions',
            field=models.CharField(choices=[('Напишите вашу фамилию', 'Напишите вашу фамилию'), ('Напишите ваше имя', 'Напишите ваше имя'), ('Напишите ваше отчество', 'Напишите ваше отчество'), ('Серия водительского удостоверения', 'Серия водительского удостоверения'), ('Номер водительского удостоверения', 'Номер водительского удостоверения'), ('Введите номер лицензии', 'Введите номер лицензии'), ('Класс ТС (B, C... )', 'Класс ТС (B, C... )'), ('Выбор ТС', 'Выбор ТС'), ('Показание одометра', 'Показание одометра'), ('Для корректной работы сервиса введите ваше текущее время в формате: ЧЧ-ММ', 'Для корректной работы сервиса введите ваше текущее время в формате: ЧЧ-ММ'), ('Ваша заявка отправлена!', 'Ваша заявка отправлена!')], default='', max_length=100, verbose_name='Вопросы'),
        ),
        migrations.CreateModel(
            name='CarQuestionnaireButtons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buttons', models.ManyToManyField(related_name='car_buttons', to='botviber.Button')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.subscriber')),
            ],
            options={
                'verbose_name': 'Кнопка меню добавления автомобиля',
                'verbose_name_plural': 'Кнопки меню добавления автомобиля',
            },
        ),
    ]
