# Generated by Django 3.1.2 on 2022-04-30 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0008_auto_20220422_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaybillJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_counter', models.PositiveIntegerField(default=0, verbose_name='Количество путевых листов')),
            ],
            options={
                'verbose_name': 'Регистрация путевого листа',
                'verbose_name_plural': 'Регистрации путевых листов',
            },
        ),
        migrations.CreateModel(
            name='WaybillNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(default='', max_length=30, verbose_name='Заявитель')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='Номер телефона')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Номер путевого листа')),
                ('id_client', models.PositiveIntegerField(default=0, verbose_name='Гаражный номер')),
                ('surname', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(default='', max_length=50, verbose_name='Отчество')),
                ('ser_doc', models.CharField(default='', max_length=10, verbose_name='Серия удостоверения')),
                ('num_doc', models.CharField(default='', max_length=10, verbose_name='Номер удостоверения')),
                ('num_lic', models.CharField(default='', max_length=100, verbose_name='Номер лицензии')),
                ('kod_org_doc', models.CharField(default='', max_length=2, verbose_name='Класс ТС')),
                ('tr_reg_num', models.CharField(default='', max_length=12, verbose_name='Гос. номер ТС')),
                ('tr_mark', models.CharField(default='', max_length=50, verbose_name='Марка ТС')),
                ('tr_model', models.CharField(default='', max_length=50, verbose_name='Марка ТС')),
                ('odometer_value', models.CharField(default='', max_length=8, verbose_name='Показание одометра при выезде')),
                ('date', models.CharField(default='', max_length=10, verbose_name='Дата выезда')),
                ('time', models.CharField(default='', max_length=5, verbose_name='Время выезда')),
                ('time_zone', models.CharField(default='3', max_length=2, verbose_name='Часовой пояс')),
                ('arrival_time', models.CharField(blank=True, default='', max_length=5, verbose_name='Время возвращения')),
                ('start_tech_state', models.CharField(blank=True, default='Исправен', max_length=10, verbose_name='Тех.состояние ТС и прицепа в момент выезда')),
                ('finish_tech_state', models.CharField(blank=True, default='', max_length=10, verbose_name='Тех.состояние ТС и прицепа по возвращению')),
                ('final_odometer_value', models.CharField(blank=True, default='', max_length=8, verbose_name='Показание одометра при возвращении')),
                ('fuel_residue', models.CharField(blank=True, default='', max_length=3, verbose_name='Остаток горючего')),
                ('special_marks', models.CharField(blank=True, default='', max_length=50, verbose_name='Особые отметки')),
                ('mechanic_signature', models.CharField(blank=True, default='', max_length=25, verbose_name='Подпись механика')),
                ('driver_signature', models.CharField(blank=True, default='', max_length=25, verbose_name='Подпись водителя')),
            ],
            options={
                'verbose_name': 'Запись в журнале',
                'verbose_name_plural': 'Записи в журнале',
            },
        ),
        migrations.CreateModel(
            name='WaybillEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='Номер телефона')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Номер путевого листа')),
                ('id_client', models.PositiveIntegerField(default=0, verbose_name='Гаражный номер')),
                ('surname', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(default='', max_length=50, verbose_name='Отчество')),
                ('ser_doc', models.CharField(default='', max_length=10, verbose_name='Серия удостоверения')),
                ('num_doc', models.CharField(default='', max_length=10, verbose_name='Номер удостоверения')),
                ('num_lic', models.CharField(default='', max_length=100, verbose_name='Номер лицензии')),
                ('kod_org_doc', models.CharField(default='', max_length=2, verbose_name='Класс ТС')),
                ('tr_reg_num', models.CharField(default='', max_length=12, verbose_name='Гос. номер ТС')),
                ('tr_mark', models.CharField(default='', max_length=50, verbose_name='Марка ТС')),
                ('tr_model', models.CharField(default='', max_length=50, verbose_name='Модель ТС')),
                ('odometer_value', models.CharField(default='', max_length=8, verbose_name='Показание одометра при выезде')),
                ('time_zone', models.CharField(default='3', max_length=2, verbose_name='Часовой пояс')),
                ('date', models.CharField(default='', max_length=10, verbose_name='Дата выезда')),
                ('time', models.CharField(default='', max_length=5, verbose_name='Время выезда')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.subscriber', verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Регистрационные данные для путёвки',
                'verbose_name_plural': 'Регистрационные данные для путёвок',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=100, verbose_name='Город')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Имя и фамилия')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='Номер телефона')),
                ('car_number', models.CharField(default='', max_length=20, verbose_name='Госномер')),
                ('car_model', models.CharField(default='', max_length=50, verbose_name='Марка и модель')),
                ('number_of_seats', models.CharField(default='', max_length=50, verbose_name='Кол-во посадочных мест')),
                ('car_year_made', models.CharField(default='', max_length=20, verbose_name='Год выпуска')),
                ('car_type', models.CharField(default='', max_length=50, verbose_name='Тип кузова')),
                ('car_color', models.CharField(default='', max_length=50, verbose_name='Тип кузова')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.subscriber', verbose_name='Соискатель')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=10, verbose_name='id заказа')),
                ('service', models.CharField(default='', max_length=100, verbose_name='Сервис')),
                ('tariff', models.CharField(default='', max_length=300, verbose_name='Тариф')),
                ('from_location', models.CharField(default='', max_length=300, verbose_name='Откуда')),
                ('to_location', models.CharField(default='', max_length=300, verbose_name='Куда')),
                ('order_cost', models.IntegerField(default=0, verbose_name='Стоимость заказа, руб. ')),
                ('comment', models.CharField(default='', max_length=300, verbose_name='Комментарий')),
                ('ord_success', models.BooleanField(default=False, verbose_name='Заказ принят водителем')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.subscriber', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='LicensingQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(default='', max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='Номер телефона')),
                ('car_number', models.CharField(default='', max_length=20, verbose_name='Госномер')),
                ('car_brand', models.CharField(default='', max_length=50, verbose_name='Марка автомобиля')),
                ('car_model', models.CharField(default='', max_length=50, verbose_name='Модель автомобиля')),
                ('photo_passport_first_path', models.CharField(default='/home/r/rfkemeou/kemerovo/public_html/HelloDjango/media\\no_photo.png', max_length=512, verbose_name='Первая страница паспорта')),
                ('photo_passport_reg_path', models.CharField(default='/home/r/rfkemeou/kemerovo/public_html/HelloDjango/media\\no_file.jpg', max_length=512, verbose_name='Прописка')),
                ('photo_sts_front_side_path', models.CharField(default='/home/r/rfkemeou/kemerovo/public_html/HelloDjango/media\\no_photo.png', max_length=512, verbose_name='СТС передняя сторона')),
                ('photo_sts_back_side_path', models.CharField(default='/home/r/rfkemeou/kemerovo/public_html/HelloDjango/media\\no_photo.png', max_length=512, verbose_name='СТС задняя сторона')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.subscriber', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Анкета лицензирования',
                'verbose_name_plural': 'Анкеты лицензирования',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(default='Модель не указана', max_length=50, verbose_name='Марка автомобиля')),
                ('car_model', models.CharField(default='Модель не указана', max_length=50, verbose_name='Модель автомобиля')),
                ('car_number', models.CharField(default='Номер не указан', max_length=50, unique=True, verbose_name='Гос. номер автомобиля')),
                ('car_licensing_number', models.CharField(default='', max_length=100, verbose_name='Лиценз. номер автомобиля')),
                ('is_blocked', models.BooleanField(default=True, verbose_name='Доступен')),
                ('car_owner', models.ManyToManyField(blank=True, related_name='cars', to='customer.Subscriber', verbose_name='Владелец автомобиля')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
