# Generated by Django 3.1.2 on 2022-05-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_licensing_number',
            field=models.CharField(default='', max_length=255, verbose_name='Лиценз. номер автомобиля'),
        ),
        migrations.AlterField(
            model_name='waybillentry',
            name='num_lic',
            field=models.CharField(default='', max_length=255, verbose_name='Номер лицензии'),
        ),
        migrations.AlterField(
            model_name='waybillnote',
            name='num_lic',
            field=models.CharField(default='', max_length=255, verbose_name='Номер лицензии'),
        ),
    ]
