# Generated by Django 3.1.2 on 2022-05-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220503_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_licensing_number',
            field=models.CharField(default='Лиц. номер не указан', max_length=255, verbose_name='Лиценз. номер автомобиля'),
        ),
        migrations.AlterField(
            model_name='waybillentry',
            name='kod_org_doc',
            field=models.CharField(default='B', max_length=2, verbose_name='Класс ТС'),
        ),
        migrations.AlterField(
            model_name='waybillnote',
            name='kod_org_doc',
            field=models.CharField(default='B', max_length=2, verbose_name='Класс ТС'),
        ),
        migrations.AlterField(
            model_name='waybillnote',
            name='tr_model',
            field=models.CharField(default='', max_length=50, verbose_name='Модель ТС'),
        ),
    ]
