# Generated by Django 3.1.2 on 2022-05-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20220507_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vehicle_class',
            field=models.CharField(default='B', max_length=2, verbose_name='Класс ТС'),
        ),
    ]
