# Generated by Django 3.1.2 on 2022-06-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_car_vehicle_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='link_for_payment',
            field=models.URLField(blank=True, verbose_name='Ссылка для оплаты'),
        ),
    ]
