# Generated by Django 3.1.2 on 2023-09-20 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20230912_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizational_and_legal_forms', models.CharField(choices=[('LLC', 'ООО'), ('IndividualEntrepreneur', 'ИП'), ('SelfEmployed', 'Самозанятый')], default='IndividualEntrepreneur', max_length=25, verbose_name='Организационно-правовая форма')),
                ('name', models.CharField(default='', max_length=128, verbose_name='Название организации')),
                ('contract_number', models.CharField(default='', max_length=20, verbose_name='Номер контракта')),
                ('EDS_org_name', models.CharField(default='', max_length=128, verbose_name='ЭЦП. Название организации')),
                ('EDS_valid_from', models.CharField(default='', max_length=25, verbose_name='ЭЦП действительна с')),
                ('EDS_valid_to', models.CharField(default='', max_length=25, verbose_name='ЭЦП действительна по')),
                ('INN', models.CharField(default='', max_length=25, unique=True, verbose_name='ИНН')),
                ('KPP', models.CharField(default='', max_length=25, verbose_name='КПП')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='validity_period_of_permit',
        ),
        migrations.AddField(
            model_name='car',
            name='permission',
            field=models.BooleanField(default=False, verbose_name='Разрешение такси'),
        ),
        migrations.AddField(
            model_name='waybillnote',
            name='organization',
            field=models.CharField(default='', max_length=128, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='car',
            name='permission_pdf',
            field=models.FileField(blank=True, default=None, max_length=255, upload_to='permission_taxi', verbose_name='Загрузить документ'),
        ),
        migrations.AddField(
            model_name='car',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='waybillentry',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.organization', verbose_name='Организация'),
        ),
    ]
