# Generated by Django 3.1.2 on 2023-09-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20230920_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='OGRN',
            field=models.CharField(default='', max_length=25, unique=True, verbose_name='ОГРН'),
        ),
    ]
