# Generated by Django 3.1.2 on 2023-09-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20230920_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contract_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер контракта'),
        ),
    ]
