# Generated by Django 3.1.2 on 2023-09-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20230920_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='is_blocked',
            new_name='is_available',
        ),
    ]
