# Generated by Django 3.1.2 on 2023-10-26 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20230920_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='EDS_valid_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='ЭЦП действительна с'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='EDS_valid_to',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='ЭЦП действительна по'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=264, verbose_name='Название организации'),
        ),
    ]
