# Generated by Django 3.1.2 on 2023-10-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20231026_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='EDS_valid_from',
            field=models.CharField(default='', max_length=25, verbose_name='ЭЦП действительна с'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='EDS_valid_to',
            field=models.CharField(default='', max_length=25, verbose_name='ЭЦП действительна по'),
        ),
    ]
