# Generated by Django 3.1.2 on 2023-10-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20231027_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybillentry',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Путевой лист закрыт?'),
        ),
        migrations.AddField(
            model_name='waybillentry',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Счётчик путевых листов'),
        ),
    ]
