# Generated by Django 3.1.2 on 2023-10-26 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20231027_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('EDS_number', models.CharField(default='', max_length=25, verbose_name='Номер лицензии')),
                ('EDS_valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='ЭЦП действительна с')),
                ('EDS_valid_to', models.DateField(default=django.utils.timezone.now, verbose_name='ЭЦП действительна по')),
                ('EDS_address', models.CharField(default='', max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Диспетчер-нарядчик',
                'verbose_name_plural': 'Диспетчеры-нарядчики',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('EDS_number', models.CharField(default='', max_length=25, verbose_name='Номер лицензии')),
                ('EDS_valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='ЭЦП действительна с')),
                ('EDS_valid_to', models.DateField(default=django.utils.timezone.now, verbose_name='ЭЦП действительна по')),
                ('EDS_address', models.CharField(default='', max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('EDS_number', models.CharField(default='', max_length=25, verbose_name='Номер лицензии')),
                ('EDS_valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='ЭЦП действительна с')),
                ('EDS_valid_to', models.DateField(default=django.utils.timezone.now, verbose_name='ЭЦП действительна по')),
                ('EDS_address', models.CharField(default='', max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Механик',
                'verbose_name_plural': 'Механики',
            },
        ),
    ]
