# Generated by Django 3.1.2 on 2023-10-26 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_dispatcher_doctor_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='dispatcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.dispatcher', verbose_name='Диспетчер-нарядчик'),
        ),
        migrations.AddField(
            model_name='organization',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.doctor', verbose_name='Врач'),
        ),
        migrations.AddField(
            model_name='organization',
            name='mechanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.mechanic', verbose_name='Механик'),
        ),
    ]
