# Generated by Django 3.1.2 on 2023-12-05 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_subscriber_snils'),
        ('order', '0019_auto_20231027_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organizational_and_legal_forms',
            field=models.CharField(choices=[('LLC', 'ООО'), ('IndividualEntrepreneur', 'ИП')], default='IndividualEntrepreneur', max_length=25, verbose_name='Организационно-правовая форма'),
        ),
        migrations.CreateModel(
            name='SelfEmployed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=264, verbose_name='Название организации')),
                ('legal_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Юридический адрес')),
                ('contract_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Номер контракта')),
                ('EDS_org_name', models.CharField(default='', max_length=128, verbose_name='ЭЦП. Название организации')),
                ('EDS_valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='ЭЦП действительна с')),
                ('EDS_valid_to', models.DateField(default=django.utils.timezone.now, verbose_name='ЭЦП действительна по')),
                ('INN', models.CharField(default='', max_length=25, unique=True, verbose_name='ИНН')),
                ('OGRN', models.CharField(default='', max_length=25, unique=True, verbose_name='ОГРН')),
                ('SNILS', models.CharField(blank=True, max_length=14, verbose_name='СНИЛС')),
                ('dispatcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.dispatcher', verbose_name='Диспетчер-нарядчик')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.doctor', verbose_name='Врач')),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.mechanic', verbose_name='Механик')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.subscriber', verbose_name='Самозанятый')),
            ],
            options={
                'verbose_name': 'Самозанятый',
                'verbose_name_plural': 'Самозанятые',
            },
        ),
        migrations.CreateModel(
            name='CarFileDocumentPairIntermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_pdf', models.FileField(blank=True, default=None, max_length=255, upload_to='permission_taxi', verbose_name='Загрузить разрешение водителя')),
                ('car', models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='order.car', verbose_name='Автомобиль')),
                ('self_employed', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.selfemployed')),
            ],
            options={
                'verbose_name': 'Разрешение водителя',
                'verbose_name_plural': 'Разрешения водителя',
                'unique_together': {('self_employed', 'car', 'driver_pdf')},
            },
        ),
        migrations.AddField(
            model_name='car',
            name='permission_related_pairs',
            field=models.ManyToManyField(related_name='cars', through='order.CarFileDocumentPairIntermediate', to='order.SelfEmployed', verbose_name='Разрешения водителя'),
        ),
    ]
