# Generated by Django 3.1.2 on 2023-12-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20231205_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfemployed',
            name='SNILS',
        ),
    ]
